### ISSUE TITLE
HTML5 support on destiny.gg/bigscreen?

### ISSUE THREAD

**Issue by kenifyable** [destinygg/website#104]
This is more of an enhancement than an issue.

Adding &html5=true to the iframe source will result in full HTML5 support on the latest Chrome and Firefox browsers, without affecting HLS-compatible browsers.
Only issues I've came across with this is that it isn't working if you have an extension such as https everywhere forcing an https connection through twitch.tv.

**It might not work with flash player enabled**, but having a toggle of some sort between HTML5 and flash would be nice.

Note: I haven't found this feature in [the official twitch embedding documentation](https://github.com/justintv/Twitch-API/blob/master/embed-video.md).

**Comment by cene-co-za** [comment]
This has been open for a while. I think using the standard embed is the correct implementation.
Twitch handles which player to load appropriate to the OS requesting it.
