### ISSUE TITLE
[Error] Refused to connect to wss://www.destiny.gg/ws because it does not appear in the connect-src directive of the Content Security Policy.

### ISSUE THREAD

**Issue by halfnhalf** [destinygg/website#110]
Looks like future versions of CSP2 will only allow wild cards in schema form [source](https://www.w3.org/TR/CSP2/#source_list) .  [config](https://github.com/destinygg/website/blob/master/config/nginx/dgg_csp.conf) currently just uses a wildcard and doesn't work on Safari 10 Beta.   

changing connect-src to`*:*` might be a possible solution.

**Comment by ILiedAboutCake** [comment]
This now makes chat unavailable on macOS sierra builds and iOS 10 builds. The issue can be resolved by updating the CSP headers: 

https://webkit.org/blog/6830/a-refined-content-security-policy/

**Comment by sztanpet** [comment]
make my life easier and just send a pull request with the correct CSP config please
