### ISSUE TITLE
Jump to chat with keyboard combination

### ISSUE THREAD

**Issue by bliutwo** [destinygg/website#111]
When you click on the twitch player for any reason (volume, quality change, etc.) your cursor is no longer in chat to type. Ideally, there would be a keyboard/button combination that lets you jump straight to the chat line so that you can continue typing in chat, similar to Ctrl+L or Command+L in your browser.

**Comment by KenanY** [comment]
I just attempted this for a couple minutes, and I'm thinking that it might not be possible. Cannot bind any keypress events to the player's iframe since it comes from a different origin.

``` javascript
$('.stream-element').get(0).contentWindow.document;
// => Uncaught DOMException: Blocked a frame with origin "https://www.destiny.gg" from accessing a cross-origin frame.
```

**Comment by bliutwo** [comment]
DaFeels

**Comment by cene-co-za** [comment]
I don't think we will ever implement key combinations at all.
You can use tab, but in that case you are already on the chat screen.
RIP.
