### ISSUE TITLE
Private Message Link Regex broken

### ISSUE THREAD

**Issue by xDashh** [destinygg/website#117]
The regexes for links in private messages differ on `/profile/messages` vs. `/embed/chat`.
An example link that works in chat but is broken in the profile page is `https://example.com/test@test.com/`. 

On the profile page it is shown as `test@test.com/" target="_blank">https://example.com/test@test.com/`.

**Comment by cene-co-za** [comment]
This issue has been resolved, I now use the actual chat code to parse pms in the /profile/messages section
