### ISSUE TITLE
Destiny.gg chat is stuck at connecting on ipad

### ISSUE THREAD

**Issue by muhshi4** [destinygg/website#120]
Cant connect to the chat when im. Trying to do it on my ipad :( everything should be updated and it used to work a couple of months ago

**Comment by KenanY** [comment]
FWIW, I can connect just fine with my own iPad running iOS 8.4 with Chrome 47 and Safari.

**Comment by muhshi4** [comment]
I've got iOS 10.1.1 and it doesn't work on the newest versions of chrome or safari. I tested it today on the opera mini app and the chat was working there. https://imgur.com/a/7naSQ here's what it looks like, it's stuck in the connecting thing.
