### ISSUE TITLE
Can't delink authenticated provider accounts

### ISSUE THREAD

**Issue by EvilSteel** [destinygg/website#123]
I recently subscribed to Destiny on Twitch, but my Twitch account on D.GG is linked to my reddit account, so as a result, I'm not able to use my Twitch subscription on D.GG unless I'm able to either delink my accounts or have authentication providers transfer their subscriptions to the main account.

**Comment by sztanpet** [comment]
that is correct

**Comment by sztanpet** [comment]
to get serious though, yes just register with the account you want and ask us to change your nick on d.gg, do tell us the old and the new nick
