### ISSUE TITLE
Chat randomly scrolls up due to Chrome smooth scrolling

### ISSUE THREAD

**Issue by vaindil** [destinygg/website#125]
Every now and then chat will randomly jump up (scroll up) in Chrome. It has the usual effect of pausing chat as if you had manually scrolled up. I keep d.gg open on a monitor that I don't usually interact with unless I'm actually chatting; it happens whether I'm using the page or not. Disabling smooth scrolling at `chrome://flags/#smooth-scrolling` fixes this, but that's obviously not ideal.

**Comment by sztanpet** [comment]
yes, sounds like a browser bug and is very annoying so probably should work around it somehow for the time being

**Comment by cene-co-za** [comment]
Seems that the issue has been resolved. It was difficult to reproduce, but it seems after the CSS change I did not see it happened again. 

There where a few places that mentioned this css property, here is an example.
https://github.com/WICG/ScrollAnchoring/blob/master/explainer.md

Commit with the fix.
https://github.com/destinygg/website/commit/fb43fd55eaad1786187cf584fb2cba443e5b38c1
