### ISSUE TITLE
Allow chat input to be vertically resized

### ISSUE THREAD

**Issue by ChristopherJHart** [destinygg/website#130]
This is an enhancement, not necessarily an issue.

A common problem I've run into is the inability to vertically resize the chat input form. This is particularly a nuisance when a message I'd like to send is of paragraph-length, but the chat window has been horizontally resized to take up <25% of the screen, as the below image shows.

http://i.imgur.com/ozDQ424.jpg

I believe this could be done relatively easily through modifying the CSS.

**Comment by cene-co-za** [comment]
Chat input is now a text box, although not perfect, about 50% better.
Not going to implement this request for various reasons.
