### ISSUE TITLE
Direct messages in d.gg chat

### ISSUE THREAD

**Issue by Pixelshroom** [destinygg/website#133]
When talking in the new d.gg direct messages tabs the messages received are not displayed properly. 

The chat I am talking about is accessed by clicking the direct messages icon on the bottom left, then clicking the chatters name in which you received a direct message from. If you view messages send by simply typing  /w (name) (message) display fine, however if you decide to chat by directly imputing into the new chat window, the problem arises

It only displays your name, not the name of the user that you are receiving messages from. The image linked below is an example, I have circled the messages I received in red. 

![d gg bug](https://cloud.githubusercontent.com/assets/29221672/26815503/5e63bd3c-4a52-11e7-8987-329220544c16.jpg)

**Comment by JJAYL** [comment]
AFAIK this only happens when you have in-line messages option ticked in the settings

**Comment by cene-co-za** [comment]
This should now be fixed. (in some commit) Im going through and testing some of these older issues.
