### ISSUE TITLE
Flashing emotes don't appear

### ISSUE THREAD

**Issue by ryjin** [destinygg/website#134]
Browser: Firefox 53.0.3

WEEWOO and DANKMEMES both appear as blank spaces and then appear. When I hover over the emotes they disappear again and then come back.

**Comment by cene-co-za** [comment]
Is this still a problem? I'm unable reproduce. No-one else is complaining. 
Closing until reply.

**Comment by ryjin** [comment]
It's still not working for me. What info would help you reproduce?

**Comment by cene-co-za** [comment]
A screenshot? do you still have bdgg installed?
Does it happen in the emote popup?

**Comment by ryjin** [comment]
capture of the emotes. http://i.imgur.com/5PEDEnQ.gif
bdgg is uninstalled. 
Other add-ons that I've got installed are BTTV, NoScript, RES, and uBlock Origin but NoScript and uBlock are disabled on d.gg. 
It does happen in the emote popup.
