### ISSUE TITLE
Tagging in d.gg

### ISSUE THREAD

**Issue by Pixelshroom** [destinygg/website#138]
You can tag anything in dgg. I can tag any word and it will be sotred. for example, if i am confused about the way the command works i will say "/tag red <user> and it will state in the chat "tag <your name> <a random color>". I have linked screenshots of be doing this exact thing and the list of tags on my account immediately after.

Screenshots in this order:1. the "/tag" command before any action.
2. Output when "/tag red CaptainAutismo " was typed into chat.
3. the "/tag" command after 

1. http://i.imgur.com/gq4FnXB.png (initial /tag)
2. http://i.imgur.com/KZuyWYX.png (/tag red captianautismo)
3. http://i.imgur.com/tjXzW1s.png (final /tag)

I am not sure if this affects chat at all, however I was quite confused when I recently tried the /tag command to show a new user how it worked. I saw the colors "red" "green" and  "blue" randomly in the list of names, and thought it was somehow showing me the colors I had tagged people. It took me 5 minutes to realize I had actaully tagged the WORDS red, green and blue. this applies to every single input. example:

http://i.imgur.com/Sjz3IOS.png (asdf was added as a tag)

**Comment by cene-co-za** [comment]
I have a fix on the way for this, should get time this evening to commit/deploy. Thanks.

**Comment by cene-co-za** [comment]
You are now only allowed to tag usernames which are in chat at the time of the tag.
The correct syntax is `/tag <nick> <color>`
