### ISSUE TITLE
Messages not working: 404 for profile.js

### ISSUE THREAD

**Issue by j4p3** [destinygg/website#139]
Private messages seem to be down as a result of a script not loading.

##To reproduce:

1. Visit https://www.destiny.gg/profile/messages

##Expected result:

Loads scripts, message functionality

##Actual result:

`profile.js` fails to load, private messages can't send

![screen shot 2017-08-10 at 5 12 28 pm](https://user-images.githubusercontent.com/1228528/29192430-66590eae-7def-11e7-9bc2-89af9545f16c.png)
![screen shot 2017-08-10 at 5 12 11 pm](https://user-images.githubusercontent.com/1228528/29192429-6658a2ca-7def-11e7-9625-2da0c9eceb66.png)
![screen shot 2017-08-10 at 5 11 24 pm](https://user-images.githubusercontent.com/1228528/29192431-665cd12e-7def-11e7-9079-bf711cb627a8.png)

**Comment by cene-co-za** [comment]
temp fixed by dgg user, fixed by me in next push.
