### ISSUE TITLE
broken: /emotes

### ISSUE THREAD

**Issue by hayksaakian** [destinygg/website#141]
![image](https://user-images.githubusercontent.com/1884787/32207152-5ccaec60-bdb7-11e7-8f91-cc27f5650965.png)

to reproduce, open chat in chrome on a mac then type /emotes in chat

chat.js:11 Uncaught TypeError: this.emoticons.join is not a function
    at e.value (chat.js:11)
    at chat.js:11
    at chat.js:1
    at Array.forEach (<anonymous>)
    at e.value (chat.js:1)
    at e.value (chat.js:11)
    at chat.js:11
    at chat.js:1
    at Array.forEach (<anonymous>)
    at e.value (chat.js:1)

**Comment by david-cako** [comment]
Untested, should fix though.

https://github.com/david-cako/website/commit/b99bb1892f672361d3198ed5ca7059dde06f4dfa

**Comment by cene-co-za** [comment]
Fixed in e40cb1d1b28e97f86dc102263345a351b6a5aa6f
