### ISSUE TITLE
Deployment documentation

### ISSUE THREAD

**Issue by blackhandcommando** [destinygg/website#142]
This is more of a question than an issue.

Is there any documentation on iis/linux deployment of this project?

**Comment by blackhandcommando** [comment]
Understood that its for nginx/php. My question was somewhat obsolete. Still the documentation is somewhat lacking, for example the database initial data commit is missing some roles.

**Comment by cene-co-za** [comment]
Unfortunately its a complex setup, and is not really designed around ease of installation.
I'll try put some effort into this asap, but can't promise anything.

Push requests are welcome.
hit me on on dgg discord or destiny.gg/chat/embed if you need some help.
