### ISSUE TITLE
two requests.

### ISSUE THREAD

**Issue by caneut** [destinygg/website#144]
When someone whispers you, you should be able to /r to whisper back. 
Get whisper, type /r, then once you hit space it autofills to "/w *lastusertowhisperyou* "

Also, while watching twitch streams on overrustle, any way to have an option to see both d.gg chat and the twitch chat? Would be nice to be able to have one chat on both sides of the screen.

I love you all.

-cane

**Comment by cene-co-za** [comment]
We are no associated with overrustle, hit them up on their chat implementation or their github projects, they are receptive.

I implemented the /r functionality a couple of weeks ago, let us know if it works :)
