### ISSUE TITLE
Unable to Reopen Chat After Closing

### ISSUE THREAD

**Issue by ALonelyTower** [destinygg/website#147]
State:
Logged into Destiny.gg through Twitch Account
Viewing Stream in Big Screen mode

Issue:
Upon closing the chat window, there's no visible indication as to how to reopen it other than to reload the browser window.  Unsure if this was intended, or not possible as the Twitch overlay is brought to the foreground after the chat window is closed.

![chat_window_before_closing](https://user-images.githubusercontent.com/42524361/48758553-404d8e80-ec55-11e8-922a-98eb1f96e2b7.PNG)
![after_closing_chat_window](https://user-images.githubusercontent.com/42524361/48758633-8f93bf00-ec55-11e8-8af1-8e9fd9726e38.PNG)

**Comment by cene-co-za** [comment]
This is intentional, one has to "refresh" to get the chat back. The amount of people that use the functionality, does not warrant the additional code. Less code where possible has been a successful strategy ... so far.
