### ISSUE TITLE
M key shortcut to mute and unmute stream

### ISSUE THREAD

**Issue by Tdavis22** [destinygg/website#148]
A user suggested that the m key should mute and unmute the stream. This is a functionality of twitch.tv but is missing from destiny.gg. (I think the user might be mistaken and the shortcut is only available with the extension BetterTwitchTV?)

**Comment by pjeweb** [comment]
this seems to work fine currently with both twitch and youtube embeds. the embed has to have focus - of course.

**Comment by Tdavis22** [comment]
You're right that this is currently working. I'll close the ticket.
