### ISSUE TITLE
Shop Images and podcast thumbnails don't show up in Firefox

### ISSUE THREAD

**Issue by kinmen** [destinygg/website#149]
![image](https://user-images.githubusercontent.com/8571556/49424691-3a28d900-f750-11e8-9f23-d03d7e24cfd2.png)

Seems to be issue with css, just using content: url.
`
img.dbh-mug1 {
    content: url(img/dbh-mug1.png);
}
`
https://stackoverflow.com/questions/17907833/content-url-does-not-display-image-on-firefox-browser
https://stackoverflow.com/questions/47183886/css-content-image-not-showing-up-on-firefox

I don't really know shit about FE, so sorry didn't come up with anything good enough for a PR :/

**Comment by cene-co-za** [comment]
thanks, working on it. appreciate the feedback!
