### ISSUE TITLE
When the only auth provider a user has, bans that user, they are effectively locked out of their account

### ISSUE THREAD

**Issue by cene-co-za** [destinygg/website#160]
Obvious answer is to provide a d.gg password, we purposely did not want to handle credentials.

**Comment by georgetdawson** [comment]
Why was it chosen not to handle credentials?

**Comment by ILiedAboutCake** [comment]
I don't believe this is anything we need to improve on, end users have the option of adding more than one provider. Twitter and Reddit also continue to allow OAuth access after a perma ban.

Locked out users can always message `contact@destiny.gg` to regain access. Current requests are 1-2/month so I don't feel the time is worth on this issues.
