### ISSUE TITLE
Remove Line in 'donate.php'

### ISSUE THREAD

**Issue by zipzopzubitybop** [destinygg/website#174]
Petition to scrap this unneeded element.

https://github.com/destinygg/website/blob/4dfa4df020bec14a3f427f1c159b1cf648165c15/views/donate.php#L25

**Comment by ahtee** [comment]
Maybe would look better as a reduced width page with a layout of

 a button to donate through stream labs
------------- or ----------------
Form to donate:
- email
- amount
- note/message
continue button

order being the preference of receiving donations

**Comment by mix-ologist** [comment]
https://github.com/destinygg/website/pull/225 aims to resolve this issue by moving the link below the form.

**Comment by ILiedAboutCake** [comment]
fixed in #225
