### ISSUE TITLE
Unable to login via twitch after deleting account

### ISSUE THREAD

**Issue by derDeidra** [destinygg/website#175]
For one reason or another I had deleted my account on d.gg.  The account was initially created from Twitch.  Now, when I attempt to login via Twitch I get an error on d.gg saying:

Error
Invalid user status Redacted

Does this mean my account got marked "redacted" instead of being totally removed from the database?  If so, there a way I can get my account back?

Any help would be much appreciated.

**Comment by ILiedAboutCake** [comment]
Submit an email to contact@destiny.gg with the account name and auth provider
