### ISSUE TITLE
Dynamic update to store frontpage links

### ISSUE THREAD

**Issue by ILiedAboutCake** [destinygg/website#176]
The storefront provider has been moved away from DBH to another vendor, these links should be set within a configuration file, or removed from the site. Currently these images and links are hardcoded in the file below:

https://github.com/destinygg/website/blob/master/lib/Destiny/Controllers/HomeController.php#L17-L50

**Comment by Dthomas810** [comment]
It would break when if they mess with their front page too much, but this should be doable. Is there a better way to pull data from https://dggstore.com/ ? I'll start working on it cause why not, but it would be easier and less maintenance if there was an api somewhere.

**Comment by 11k** [comment]
Hey @Dthomas810, I actually finished working on this issue just a few minutes after you commented. It sounds like you plan on fetching the data from the new vendor and updating things dynamically. I just moved the `$merchandise` array into the appropriate config file to make updating links easier. Maybe that's good enough? 🤷‍♂️

**Comment by Dthomas810** [comment]
@11k Yea I figured that's what was originally in mind but I figured it could be done better than that, even if it's still a lil jank

**Comment by Dthomas810** [comment]
@ILiedAboutCake I'm having trouble getting the site running, I've got wamp running running and I've done all the commands in the readme but at best I just get this
![image](https://user-images.githubusercontent.com/32943574/81269531-0c178a80-900f-11ea-9207-d5ce38d2946a.png) ideas?
