### ISSUE TITLE
Update Twitch API to be use consistent OAuth Scope

### ISSUE THREAD

**Issue by ILiedAboutCake** [destinygg/website#181]
Twitch recently made changes to the authentication scope to require tokens on all requests: https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

```What’s changing?
Starting on April 30, 2020 May 1, 2020, Helix will require the following:

Use of OAuth across all endpoints, either via an app access token or user access token.
The client ID provided in the corresponding header must match the client ID used to generate the OAuth token.
```

Inside of the Cron scheduler there is a job running failing every minute: 
```
[2020-05-12 14:56:04] web.ERROR: Error handling twitch hook cron task Error sending twitch webhook subscription request. {"error":"Unauthorized","status":401,"message":"OAuth token is missing"} [] []
```

According to the PHP errors occurring at the time, the errors appear to be coming from https://github.com/destinygg/website/blob/master/lib/Destiny/Tasks/StreamInfo.php but there are likely other places the API is being improperly accessed too, these endpoints should be modernized.

**Comment by 11k** [comment]
Currently working on this and wanted to post a small update. The `StreamInfo` cron task uses `TwitchApiService` to fetch the stream status via the Kraken v5 API. The new OAuth token requirement only applies to the Helix API, which is used by `TwitchWebHookService` in the `TwitchWebhook` task. [Here's](https://github.com/destinygg/website/blob/0bc7458f7905bdb8c6b9dfdd19975b12b44d7003/lib/Destiny/Tasks/TwitchWebhook.php#L30) where the error is logged.

Assuming we're fine with sticking to the Kraken API when it's an option, `TwitchWebHookService` is the only class that needs updating.
