### ISSUE TITLE
Stream betting feature

### ISSUE THREAD

**Issue by xtphty** [destinygg/website#21]
Long term suggestion, just wanted to write it down.  I've seen some stream chats do this, users bet on whether the streamer will win / lose the game.  When the game is over the streamer (can be automated with League APIs), will declare a win or loss, and the pot gets distributed accordingly.  It doesnt really need to be tied into chat, but the real time / shared aspect in chat definitely adds excitement.  
- On the back end we would need to track the user's 'cash', and betting stats (win / loss ratio + streak).  Later on, this could maybe get tied into the fantasy league system somehow, as a new way to earn credits.
- Inside chat interface, add a button that opens a popover similar to the chat settings / user list.  This will allow the user to place bets, show their cash, etc.  
  - When a new bet starts flash the button, or show an alert in chat (could be tied into the broadcasts system sztanpet has an issue for). 
  - During the betting period, show a real-time updating tally of the total pot, and the distribution of win/loss bets.
  - When betting ends, show the top 5 or so winners.
- Create automatic mode with the League API, to detect when a bet should be started, ended, and the result (win / loss)

**Comment by georgetdawson** [comment]
This would be awesome
