### ISSUE TITLE
YouTube Membership Integration 

### ISSUE THREAD

**Issue by ILiedAboutCake** [destinygg/website#222]
We need to establish if this is even possible, we already use Google as an OAuth provider. If a user has a YouTube membership to the Destiny channel, they should be given a subscriber flair and chat color for T1, similar to how Twitch subs work. Aim for this to be automated and follow the same user experience as subbing on Twitch.

**Comment by chaoky** [comment]
there's this
https://developers.google.com/youtube/v3/docs/members/list
