### ISSUE TITLE
OperaGX Twitch Bigscreen problems

### ISSUE THREAD

**Issue by ZombGuy** [destinygg/website#237]
I'm unaware of what causes this in specific however I know it is not due to the twitch player in general because it works when watching streams on twitch. However when I use the big screen for twitch on OperaGX it typically will skip and freeze or pause repeatedly. It is only twitch specific, I've tested with youtube stream embeds and it works fine without any problems. As far as I know its just solely surrounding twitch streams. I haven't heard of anyone else having this problem so I also don't know if it is just specific to my browser due to a setting that might've been changed or whether it is a problem that can be recreated by someone else. If someone could help verify this issue by trying dgg's big-screen with twitch on OperaGX that would be awesome. Its only the big-screen and everything else including chat and chat pop-outs work fine from what I can tell.

This is also what appears to pop-up in the console on load as well [Here is a screenshot from Gyazo.](https://gyazo.com/086aace3e57c5e951d6bfa36470de109)

Here is also a video of what I see on my end as well as the console [https://youtu.be/pdJ0b-AdjtE](https://youtu.be/pdJ0b-AdjtE) 
It is typically an unprompted pause and the stream stops and doesn't do anything it seems.

Its pretty low priority since its just a specific browser problem but OperaGX is a gamer browser so I feel like I should at least report it. OOOO

**Comment by ILiedAboutCake** [comment]
Sadly not anything we can do but I thank you for the detailed bug report. Our embed for Twitch is just using their embedded resource: https://dev.twitch.tv/docs/embed/video-and-clips#interactive-frames-for-live-streams-and-vods

This is personal opinion but Twitch support for the embed is laughable, Edge users get a 5-10 second delay with no reason why.

A recommendation I have if you wish to use Opera to watch the stream live is to watch the YouTube embed. You can swap out the video ID for Destiny's livestream https://www.destiny.gg/bigscreen#youtube/DDU-rZs-Ic4
