### ISSUE TITLE
Allow oauth token to authenticate user in chat

### ISSUE THREAD

**Issue by Moseco** [destinygg/website#241]
I have gone through the process described in the [oauth.md documentation](https://github.com/destinygg/website/blob/master/OAUTH.md). From what I can tell this token can only be used to get user information from /api/userinfo?token=$TOKEN, as described in the documentation. But it cannot be used to authenticate the user in the chat by sending it as a cookie with the name authtoken as described in [profile->developer section->connections page.](https://www.destiny.gg/profile/developer)

While creating a token/login key using the website on the [same page](https://www.destiny.gg/profile/developer) as above does allow the user to authenticate with the chat.

From digging around a bit it seems to caused [here](https://github.com/destinygg/website/blob/817fe7941fa8e86b831cc5f3fd6a70ff662592ce/lib/Destiny/Controllers/ApiController.php#L202) by not allowing auth tokens with a clientID.

Is it possible to extend the capability of the oauth generated token to authenticate with the chat?

Thanks!

**Comment by ILiedAboutCake** [comment]
This is by design, you need to generate logon keys to use chat. Logon key generation is not supported via oauth, has to done by the user at $website/profile/developer

**Comment by Moseco** [comment]
Is it possible for that process to be made more user friendly? For example, a client sends the user to a page to confirm the use of a login key, and then a url redirect can send them back to the client with the login key. (Sorry if this already exists and I have missed it)

**Comment by ILiedAboutCake** [comment]
No this is an anti-abuse measure
