### ISSUE TITLE
DGG channel points

### ISSUE THREAD

**Issue by Vertalli** [destinygg/website#246]
This is a feature suggestion to incorporate a system like Twitch's Channel Points into DGG. I think the prediction feature Twitch has added to the system adds interesting interactivity and could be somewhat of a substitute, and a much simplified version, of the "DGG Clicker" that never developed into anything.

**Comment by ILiedAboutCake** [comment]
low return on investment for a large codebase change, might be a future roadmap for omnisite. No plans to add to current site which is only receiving maintenance updates.
