### ISSUE TITLE
HTML special characters not correctly converted

### ISSUE THREAD

**Issue by yodigi7** [destinygg/website#259]
When hovering the youtube thumbnails, the description then has the HTML special characters spelled out rather than the actual character (`&quot;` vs `"`)

![image](https://user-images.githubusercontent.com/19217358/115934700-487a0b80-a457-11eb-926f-a32cdea8627a.png)

![image](https://user-images.githubusercontent.com/19217358/115934723-5760be00-a457-11eb-8969-e83f70f06b46.png)

**Comment by 11k** [comment]
This doesn't seem to be an issue anymore. The site's YouTube-related functionality was recently worked on and I assume the bug was inadvertently fixed.

![Screen Shot 2021-06-10 at 12 46 03 AM](https://user-images.githubusercontent.com/20373896/121486001-9e622e80-c985-11eb-99c1-4795c19422a6.png)
