### ISSUE TITLE
 Error: No authentication handler found. #2 

### ISSUE THREAD

**Issue by im663** [destinygg/website#269]
Set this repo up under a domain, and made what I believe to be the correct customization. After inputting Discord/Twitch Oauth information I get a ` Error No authentication handler found.` error when trying to login.

Here is an output log of the error:
`web.WARNING: No authentication handler found. {"trace":"#0 /www/www.destiny.gg/lib/Destiny/Controllers/LoginController.php(85): Destiny\\Common\\Authentication\\AuthenticationService->getLoginAuthHandlerByType('twitch/')\n#1 [internal function]: Destiny\\Controllers\\LoginController->authByType(Array, Object(Destiny\\Common\\Request))\n#2 /www/www.destiny.gg/lib/Destiny/Common/Application.php(224): ReflectionMethod->invokeArgs(Object(Destiny\\Controllers\\LoginController), Array)\n#3 /www/www.destiny.gg/lib/Destiny/Common/Application.php(111): Destiny\\Common\\Application->executeController(Object(Destiny\\Common\\Routing\\Route), Object(Destiny\\Common\\Request), Object(Destiny\\Common\\Response), Object(Destiny\\Common\\ViewModel))\n#4 /www/www.destiny.gg/public/index.php(53): Destiny\\Common\\Application->executeRequest(Object(Destiny\\Common\\Request))\n#5 {main}"} []`

**Comment by im663** [comment]
Error was fixed, was an issue with adding a trailing slash after redirect uri's. After attempting oauth logins now getting:
`[2021-06-01 05:03:05] web.CRITICAL: An exception occurred while executing 'SELECT `yt_mems`.`membershipLevelId`, `u_yt_chans`.`channelTitle`, `yt_mem_levs`.`name`             FROM `users_youtube_channels` AS `u_yt_chans`             INN\
ER JOIN `youtube_members` AS `yt_mems`                 ON `yt_mems`.`memberChannelId` = `u_yt_chans`.`channelId`             INNER JOIN `youtube_membership_levels` AS `yt_mem_levs`                 ON `yt_mem_levs`.`membershipLevelId` = \
`yt_mems`.`membershipLevelId`             WHERE `userId` = ?' with params [10]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'destinygg.users_youtube_channels' doesn't exist {"trace":"#0 /www/www.destiny.gg/vendor/doctrine\
/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 /www/www.destiny.gg/vendor/doctrine/dbal/lib/Doctrine/\
DBAL/DBALException.php(145): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 /www/www.destiny.gg/vendor/doctrine/dbal\
/lib/Doctrine/DBAL/Connection.php(913): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT `yt_mems...', Array)\n#3 /www/www.\
destiny.gg/lib/Destiny/YouTube/YouTubeMembershipService.php(134): Doctrine\\DBAL\\Connection->executeQuery('SELECT `yt_mems...', Array, Array)\n#4 /www/www.destiny.gg/lib/Destiny/Controllers/ProfileController.php(65): Destiny\\YouTube\\\
YouTubeMembershipService->getMembershipDetailsForUserId(10)\n#5 [internal function]: Destiny\\Controllers\\ProfileController->profile(Object(Destiny\\Common\\ViewModel))\n#6 /www/www.destiny.gg/lib/Destiny/Common/Application.php(224): R\
eflectionMethod->invokeArgs(Object(Destiny\\Controllers\\ProfileController), Array)\n#7 /www/www.destiny.gg/lib/Destiny/Common/Application.php(111): Destiny\\Common\\Application->executeController(Object(Destiny\\Common\\Routing\\Route)\
, Object(Destiny\\Common\\Request), Object(Destiny\\Common\\Response), Object(Destiny\\Common\\ViewModel))\n#8 /www/www.destiny.gg/public/index.php(53): Destiny\\Common\\Application->executeRequest(Object(Destiny\\Common\\Request))\n#9 \
{main}","guid":"xQuf4B8hVeEt"} []
`

**Comment by atlasesque** [comment]
Update your database [with this script](https://github.com/destinygg/website/blob/master/scripts/db/upgrade-2.29.0-30-04-2021.sql)

**Comment by im663** [comment]
Thanks for the reply, I attempted this, and got the following output `ERROR 1005 (HY000) at line 15: Can't create table `destinygg`.`users_youtube_channels` (errno: 121 "Duplicate key on write or update")`
