### ISSUE TITLE
Update your database [with this script](https://github.com/destinygg/website/blob/master/scripts/db/upgrade-2.29.0-30-04-2021.sql)

### ISSUE THREAD

**Issue by im663** [destinygg/website#270]
Update your database [with this script](https://github.com/destinygg/website/blob/master/scripts/db/upgrade-2.29.0-30-04-2021.sql)

_Originally posted by @atlasesque in https://github.com/destinygg/website/issues/269#issuecomment-852413764_

Running this script results in the following output `ERROR 1005 (HY000) at line 15: Can't create table `destinygg`.`users_youtube_channels` (errno: 121 "Duplicate key on write or update")`

I ran the update script with the following command: `mysql -udestiny -pAslanIsEvil destinygg < upgrade-2.29.0-30-04-2021.sql`

**Comment by ILiedAboutCake** [comment]
This repository is not for assisting in running clone codebases
