### ISSUE TITLE
vote feature

### ISSUE THREAD

**Issue by sztanpet** [destinygg/website#3]
separate ui for creating the poll, yet another separate ui for showing the results real-time aka strawpolls but less janky

integrate with the chat by users needing to type either a command or a simple message that is EXACTLY the option for a specific choice in the poll

**Comment by sztanpet** [comment]
some minor ui issues aside it works fine:

- if vote messages are not seen by anybody else while the vote is running, it shouldnt show up as a message in chat
- there is also a lack of feedback whether your vote was "successfull" or not, giving vote messages a new style would solve that problem also
- the /vote command is trying to be too smart imo (requiring a `?` isn't bad per se, but using it as a delimiter introduces another batch of problems, especially later on when `or` is used; introducing a vote ui is a lot of work, doing it text-based is possible: `/vote whatevertext` that just prepares the question to vote on, `/vote add option whateveroption` adds another option, etc. TL;DR maybe not do the whole thing in a single command? is this even a real issue?)
- parsing of durations is a bit off seemingly: I thought writing `/vote wat? 8h` will begin a vote that lasts for 8 hours, but it didn't and instead it gives a single option to vote for which I would think is not expected

**Comment by cene-co-za** [comment]
* will replace with "vote successful" with some visual feedback in the vote interface
* same above
* My thought behind this was in the context where there is no vote interface, what would it look like? (overrustle logs etc). Keep the command natural language as possible. (I could not get around the time string at the end)
* Screw parsing time strings .. only m or s unit is allowed - it falls back to defaults if it fails? probably should look at a standard lib to do it :(

**Comment by cene-co-za** [comment]
Other than the parsing of the question, which is up for pull requests :)
this https://github.com/destinygg/chat-gui/commit/d635812f15fc8cad89463ab75a083c177300684b should suffice. 

Closing
