### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by desertedeagle** [destinygg/website#74]
If I click the middle mouse button and try to scroll left or right, the cursor is permanently stuck as the arrow symbol for left or right scroll, and I can't highlight text, click links, click names, or chat, though scrolling still works. Refreshing changes the cursor but otherwise doesn't change anything, and the issue is still present. The only way to fix the issue is to close the tab and reopen the site, or close the browser completely and reopen it. Not sure if it's a problem here or with my browser, Chrome, but it's very easy to replicate.

**Comment by sztanpet** [comment]
duplicate issue, please search before posting new issues
