### ISSUE TITLE
Disconnecting and connecting, Can't send messages in chat

### ISSUE THREAD

**Issue by jegonzalez** [destinygg/website#75]
Hi yes i have problem with sending messages to chat idk if I'm banned from the chat or wtv it has been more than 4 months http://puu.sh/e1OJJ/c399587b0f.png my username is jegonzalez

**Comment by sztanpet** [comment]
provide some actual information like browser used, what kind of internet you have, the more the merrier

**Comment by jegonzalez** [comment]
I used mozilla firefox and google chrome, I have 10 down and 5 up cable intenet from el salvador

**Comment by sztanpet** [comment]
what version of the browsers, does the internet have NAT? come on buddy, actually useful information if you are trying to file bug here

**Comment by jegonzalez** [comment]
Version 39.0.2171.95 m (64-bit) chrome , my internet does not have NAT

**Comment by sztanpet** [comment]
http://websocketstest.com/
no errors on this page? if there are, please post the report it generates on the bottom of the page (it appears after that countdown runs out)

**Comment by jegonzalez** [comment]
http://websocketstest.com/result/433084

**Comment by sztanpet** [comment]
thanks!
something outside of our control is interfering with your websocket support
issues might be with your antivirus/firewall/router/internet provider/magic fairy
