### ISSUE TITLE
Duplicate notification popups if you have more than one chat open at a time.

### ISSUE THREAD

**Issue by cene-co-za** [destinygg/website#78]
This could be solved using local storage and some notification debounce event.

**Comment by hayksaakian** [comment]
using a service worker to manage notifications would work too

**Comment by cene-co-za** [comment]
From what I have tested, you do not get duplicate notifications, because notification.tag property has been set to the messages time-stamp (which is the same no matter how many clients you have open)

Although, I don't like the idea of the duplicate notifications being raised at all.. it seems like the way people are achieving it, and for the fact that people having duplicate multiple tabs open - it should be on them to "fix" the problem ... its probably worth not investing time into it.
https://developer.mozilla.org/en-US/docs/Web/API/Notification/tag

Thoughts?

**Comment by cene-co-za** [comment]
You definitely do not get duplicates BUT -- you can't reliably tell if the user has one of their tabs focused on the chat. If you have suggestions lemme here em. else closing.
