### ISSUE TITLE
First message sent in chat after midnight has no subscriber flair

### ISSUE THREAD

**Issue by RustleOverwhelming** [destinygg/website#80]
It's reproducible and happens after a period of inactivity that crosses midnight: http://imgur.com/HgFIUJi I obviously didn't subscribe between messages.

Last message with flair: [Mar 29 2015 00:01:21 UTC]
Message without flair: [Mar 29 2015 11:52:40 UTC]

**Comment by sztanpet** [comment]
subscriber issues will be resolved with the website2 repo
