### ISSUE TITLE
Bring back fantasy league?

### ISSUE THREAD

**Issue by hayksaakian** [destinygg/website#83]
What's holding it back?

If there was an itemized list of things preventing it from working then I could contribute to fixing it but at the moment its unclear.

**Comment by cene-co-za** [comment]
It wasn't removed because of some technical issue. It was removed because Destiny did not get into it. It was a choice to cut it out.

Destiny would have to express some interest.
In the case he does, I'd probably rewrite it --- since the API's have come a long way.
