### ISSUE TITLE
"Notification on Mention" instead of the current "Notification on Highlight"

### ISSUE THREAD

**Issue by hayksaakian** [destinygg/website#84]
Not sure when this change occurred but now i'm getting  push notifications when any of the people I've highlighted say anything.

It would be nice if we could break this into either two separate check boxes, or only send a push notification when you specifically are mentioned. 

@sztanpet said it's OK if i submit a PR, so i'll get on it

**Comment by sztanpet** [comment]
i would separate it into the existing "highlight" section as it functions currently,
and into a function where you can mark other users as interesting whose messages get highlighted with a slightly different color

**Comment by cene-co-za** [comment]
I've implemented a /tag <username> feature. This highlights specific user messages.
The /highlight combined with the custom highlight setting are turned into a regex and the message.user and message.content are checked.

Those two features seem to cover this issue.
