### ISSUE TITLE
IP bans for unrelated users with the same ip do not show the correct ban message

### ISSUE THREAD

**Issue by criminal-cutie** [destinygg/website#91]
Chat failed to reconnect. After successfully reconnecting, I received a message in my chat window that I was banned http://i.imgur.com/2kRjMId.jpg
When I log onto Destiny.gg, this is what shows in my chat window  http://imgur.com/XeJEpV3 
RTBA has said I haven't been manually muted / banned by anyone, xxtphty suggested I post screenshots here since it seemed like a bug.

**Comment by sztanpet** [comment]
not a mystery anymore since there was an alt on the same ip that got ipbanned, need to fix the ban screen to show the correct ban

**Comment by cene-co-za** [comment]
Ban information from the /baninfo command (which is run after you get banned)
Attempts to get the ban info for username or IP.
