### ISSUE TITLE
font-awesome is requesting a non-existent file

### ISSUE THREAD

**Issue by 9inevolt** [destinygg/website#93]
https://cdn.destiny.gg/vendor/font-awesome-4.3.0/fonts/fontawesome-webfont.woff2?v=4.3.0

This file doesn't exist but font-awesome is looking for it. Seems to be an optional file though...

**Comment by cene-co-za** [comment]
Fixed by @sztanpet in commit 57756df0b7589594737dbecb0c413eeca4aa8aa9
